### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DavidFeria01** [SistemasTecTlaxiaco/infografia-DavidFeria01#1]
![¿Qué es la realidad aumentada](https://user-images.githubusercontent.com/79876872/153694012-4e05b60d-27b6-405f-b062-c371c3a97742.png)

**Comment by Nancy2050** [comment]
Puntaje 16/20 (80%)
Faltan fuentes

**Comment by josealfredo79** [comment]
Bien hecho y revisado
