### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by DavidFeria01** [SistemasTecTlaxiaco/infografia-DavidFeria01#2]
![INGENIERIA DE REQUISITOS](https://user-images.githubusercontent.com/79876872/110048188-fbaa6c00-7d14-11eb-83ca-4b2e28893a37.jpg)

**Comment by ElvisS10** [comment]
Excelente trabajo! Esta todo bien especificado a excepción del contraste de las fuentes con el fondo
**Calificación: 19%**

**Comment by ThorSampy** [comment]
Este trabajo esta bien estructurado, aunque le hace falta mas color o imágenes.

**Comment by Anna-Aparicio** [comment]
Información coherente,  quizás menos texto y un poco más de color o imágenes más resaltadas

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
